settings:
  title: 'Status Page'
  url: 'https://status-page.dev.democrats.org.au' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: democrats-org-au # unique identifier
    name: democrats.org.au
    description: 'Australian Democrats' # default=empty
    url: 'https://democrats.org.au' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: australian-democrats-org-au
    name: australian-democrats.org.au
    description: 'Old Democrats Website'
    url: 'https://australian-democrats.org.au'
    method: GET
    expectStatus: 200
